[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python main.py --bot"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
BOT_TOKEN=8563945646:AAEZciBBu8szpN1FLi5D-xQO61olQu6VmIY
